
#[derive(Clone, Copy, Debug)]
pub struct Error {
    pub code: ErrorCode,
    pub line: u32,
}

#[derive(Clone, Copy, Debug)]
pub enum ErrorCode {
    ARSPSuffix,
    ARSPAsPinName,
    BadARSP,
    BadChar,
    BadEOF,
    BadNC,
    BadPin,
    BadPinCount,
    BadPower,
    BadGALType,
    BadSuffix,
    BadToken,
    DisallowedCLK,
    DisallowedARST,
    DisallowedAPRST,
    InvalidControl,
    InvertedARSP,
    InvertedControl,
    InvertedPower,
    NotAnInput,
    NotAnOutput,
    NoCLK,
    NoEquals,
    NoPinName,
    // TODO: I don't really believe in these.
    PrematureAPRST,
    PrematureARST,
    PrematureCLK,
    PrematureENABLE,
    RepeatedAPRST,
    RepeatedARST,
    RepeatedARSP,
    RepeatedCLK,
    RepeatedOutput,
    RepeatedPinName,
    RepeatedTristate,
    TooManyProducts,
    TristateReg,
    UnknownPin,
    UnmatchedTristate,
    BadVCCLocation,
    BadGNDLocation,
}

// TODO: Delete these.
const _ERROR_CODES: [&str; 49] = [
    "error in source file found",
    "Line  1: type of GAL expected",
    "unexpected end of file",
    "pinname expected after '/'",
    "max. length of pinname is 8 characters",
    "illegal character in pin declaration",
    "illegal VCC/GND assignment",
    "pin declaration: expected VCC at VCC pin",
    "pin declaration: expected GND at GND pin",
    "pinname defined twice",
    "illegal use of '/'",
    "unknown pinname",
    "NC (Not Connected) is not allowed in logic equations",
    "unknown suffix found",
    "'=' expected",
    "this pin can't be used as output",
    "same pin is defined multible as output",
    "before using .E, the output must be defined",
    "GAL22V10: AR and SP is not allowed as pinname",
    ".E, .CLK, .ARST and .APRST is not allowed to be negated",
    "mode 2: pins 12, 19 can't be used as input",
    "mode 2: pins 15, 22 can't be used as input",
    "tristate control is defined twice",
    "GAL16V8/20V8: tri. control for reg. output is not allowed",
    "tristate control without previous '.T'",
    "use GND, VCC instead of /VCC, /GND",
    "pin not allowed in equations",
    "mode 3: pins 1,13 are reserved for 'Clock' and '/OE'",
    "use of VCC and GND is not allowed in equations",
    "only one product term allowed (no OR)",
    "too many product terms",
    "use of AR and SP is not allowed in equations",
    "negation of AR and SP is not allowed",
    "no equations found",
    ".CLK is not allowed when this type of GAL is used",
    ".ARST is not allowed when this type of GAL is used",
    ".APRST is not allowed when this type of GAL is used",
    "GAL20RA10: pin 1 can't be used in equations",
    "GAL20RA10: pin 13 can't be used in equations",
    "AR, SP: no suffix allowed",
    "AR or SP is defined twice",
    "missing clock definition (.CLK) of registered output",
    "before using .CLK, the output must be defined",
    "before using .ARST, the output must be defined",
    "before using .APRST the output must be defined",
    "several .CLK definitions for the same output found",
    "several .ARST definitions for the same output found",
    "several .APRST definitions for the same output found",
    "use of .CLK, .ARST, .APRST only allowed for registered outputs"
];

fn error_string(err_code: ErrorCode) -> &'static str {
    match err_code {
        ErrorCode::ARSPAsPinName => "GAL22V10: AR and SP is not allowed as pinname",
        ErrorCode::ARSPSuffix => "AR, SP: no suffix allowed",
        ErrorCode::BadARSP => "use of AR and SP is not allowed in equations",
        ErrorCode::BadNC => "NC (Not Connected) is not allowed in logic equations",
        ErrorCode::BadChar => "bad character in input",
        ErrorCode::BadEOF => "unexpected end of file",
        ErrorCode::BadGALType => "Line  1: type of GAL expected",
        ErrorCode::BadPin => "illegal character in pin declaration",
        ErrorCode::BadPinCount => "wrong number of pins",
        ErrorCode::BadPower => "use of VCC and GND is not allowed in equations",
        ErrorCode::BadSuffix => "unknown suffix found",
        ErrorCode::BadToken => "unexpected token",
        ErrorCode::InvertedARSP => "negation of AR and SP is not allowed",
        ErrorCode::InvalidControl => "use of .CLK, .ARST, .APRST only allowed for registered outputs",
        ErrorCode::InvertedControl => ".E, .CLK, .ARST and .APRST is not allowed to be negated",
        ErrorCode::InvertedPower => "use GND, VCC instead of /VCC, /GND",
        ErrorCode::NotAnInput => "pin not allowed in equations",
        ErrorCode::NotAnOutput => "this pin can't be used as output",
        ErrorCode::NoCLK => "missing clock definition (.CLK) of registered output",
        ErrorCode::NoPinName => "pinname expected after '/'",
        ErrorCode::NoEquals => "'=' expected",
        ErrorCode::PrematureAPRST => "before using .APRST the output must be defined",
        ErrorCode::PrematureARST => "before using .ARST, the output must be defined",
        ErrorCode::PrematureCLK => "before using .CLK, the output must be defined",
        ErrorCode::PrematureENABLE => "before using .E, the output must be defined",
        ErrorCode::RepeatedAPRST => "several .APRST definitions for the same output found",
        ErrorCode::RepeatedARST => "several .ARST definitions for the same output found",
        ErrorCode::RepeatedARSP => "AR or SP is defined twice",
        ErrorCode::RepeatedCLK => "several .CLK definitions for the same output found",
        ErrorCode::RepeatedOutput => "same pin is defined multible as output",
        ErrorCode::RepeatedPinName => "pinname defined twice",
        ErrorCode::RepeatedTristate => "tristate control is defined twice",
        ErrorCode::TooManyProducts => "too many product terms",
        ErrorCode::TristateReg => "GAL16V8/20V8: tri. control for reg. output is not allowed",
        ErrorCode::UnknownPin => "unknown pinname",
        ErrorCode::UnmatchedTristate => "tristate control without previous '.T'",
        ErrorCode::BadVCCLocation => "pin declaration: expected VCC at VCC pin",
        ErrorCode::BadGNDLocation => "pin declaration: expected GND at GND pin",
        ErrorCode::DisallowedCLK => ".CLK is not allowed when this type of GAL is used",
        ErrorCode::DisallowedARST => ".ARST is not allowed when this type of GAL is used",
        ErrorCode::DisallowedAPRST => ".APRST is not allowed when this type of GAL is used",
    }
}

// Adapt an ErrorCode to an Error.
pub fn at_line<Val>(line: u32, res: Result<Val, ErrorCode>) -> Result<Val, Error> {
   res.map_err(|e| Error { code: e, line: line })
}

pub fn print_error(err: Error) {
    println!("Error in line {}: {}", err.line, error_string(err.code));
}
